version: "v1.0"
name: Using Environment Variable.
semaphore_image: standard
blocks:
 - name: Environment variables
   build:
      jobs:
        - name: Inspect Environment variables
          commands:
            - echo $SEMAPHORE_PIPELINE_ID
            - echo $VAR1
            - echo $PI
      env_vars:
           - name: VAR1
             value: Environment Variable 1
           - name: PI
             value: "3.14159"