version: "v1.0"
name: epilogue and prologue YAML example.
semaphore_image: standard
blocks:
 - name: Inspect Linux environment
   build:
      jobs:
        - name: Execute hw.go 
          commands:
            - echo $SEMAPHORE_PIPELINE_ID
            - echo $HOME
            - echo $SEMAPHORE_GIT_DIR
            - pwd
      prologue:
          commands:
            - checkout
            - cd $SEMAPHORE_GIT_DIR
      epilogue:
          commands:
            - echo $SEMAPHORE_JOB_RESULT
            - echo $SEMAPHORE_PIPELINE_ID