version: "v1.0"
name: using cmd_file.
semaphore_image: standard
blocks:
 - name: Calling external text file
   build:
      jobs:
        - name: Build 1 - Job 3
          cmd_file: /home/runner/goDemo/command_file
