version: "v1.0"
name: Using the cmd_file command.
semaphore_image: standard
blocks:
 - name: Calling external command file
   build:
      jobs:
        - name: Execute command_file
         cmd_file: $SEMAPHORE_GIT_DIR/command_file
